### ISSUE TITLE
Does it support "SELECT * FROM 11111.table1"  ?

### ISSUE THREAD

**Issue by liyinxin** [xwb1989/sqlparser#78] opened 2024-05-16 03:36 UTC
Does it support "SELECT * FROM 11111.table1"  ?

I get this erorr:
SQL parsing error:syntax error at position 21 near '11111.'

**Comment by bramp** [comment] 2024-05-16 03:41
I don't think that's a valid database/table identifier. Try wrapping it in backticks.

```
SELECT * FROM `11111`.table1
```

**Comment by liyinxin** [comment] 2024-05-16 08:37
OK, I will try it

**Comment by liyinxin** [comment] 2024-05-16 08:40
`SELECT * FROM `11111`.table1`

Thanks it works.

**Comment by samjewell** [comment] 2024-11-12 10:14
Can you close this issue in that case? It's a bit distracting, when looking at the open issues on this repo

**Comment by bramp** [comment] 2024-11-12 15:57
Working as intended

**Closed as completed by bramp** 2024-11-12 15:57 UTC
